const CareerData = [
    { id: 1, title: "Software Engineer", image: "/images/software-engineer.jpg" },
    { id: 2, title: "Data Scientist", image: "/images/data-scientist.jpg" },
    { id: 3, title: "AI Specialist", image: "/images/ai-specialist.jpg" },
    { id: 4, title: "Cybersecurity Expert", image: "/images/cybersecurity.jpg" },
    { id: 5, title: "Blockchain Developer", image: "/images/blockchain.jpg" },
    { id: 6, title: "UX/UI Designer", image: "/images/ui-ux.jpg" },
    { id: 7, title: "Digital Marketer", image: "/images/digital-marketing.jpg" },
    { id: 8, title: "Cloud Engineer", image: "/images/cloud-engineer.jpg" },
    { id: 9, title: "Product Manager", image: "/images/product-manager.jpg" },
    { id: 10, title: "Game Developer", image: "/images/game-dev.jpg" },
    { id: 11, title: "Mechanical Engineer", image: "/images/mechanical.jpg" },
    { id: 12, title: "Robotics Engineer", image: "/images/robotics.jpg" },
    { id: 13, title: "Biotech Researcher", image: "/images/biotech.jpg" },
    { id: 14, title: "Healthcare AI Specialist", image: "/images/healthcare-ai.jpg" },
    { id: 15, title: "Legal Tech Consultant", image: "/images/legal-tech.jpg" },
    { id: 16, title: "IoT Engineer", image: "/images/iot.jpg" },
    { id: 17, title: "AR/VR Developer", image: "/images/ar-vr.jpg" },
    { id: 18, title: "Finance Analyst", image: "/images/finance-analyst.jpg" },
    { id: 19, title: "Business Consultant", image: "/images/business-consultant.jpg" },
    { id: 20, title: "E-commerce Specialist", image: "/images/ecommerce.jpg" },
    { id: 21, title: "Data Engineer", image: "/images/data-engineer.jpg" },
    { id: 22, title: "Network Administrator", image: "/images/network-admin.jpg" },
    { id: 23, title: "AI Ethics Consultant", image: "/images/ai-ethics.jpg" },
    { id: 24, title: "VR Game Designer", image: "/images/vr-game-designer.jpg" },
    { id: 25, title: "Astronomer", image: "/images/astronomer.jpg" },
    { id: 26, title: "Nanotech Scientist", image: "/images/nanotech.jpg" },
    { id: 27, title: "Psychologist", image: "/images/psychologist.jpg" },
    { id: 28, title: "Fitness Coach", image: "/images/fitness-coach.jpg" },
    { id: 29, title: "Electric Vehicle Engineer", image: "/images/ev-engineer.jpg" },
    { id: 30, title: "Solar Energy Specialist", image: "/images/solar-energy.jpg" },
    { id: 31, title: "Marine Biologist", image: "/images/marine-biologist.jpg" },
    { id: 32, title: "Quantum Computing Researcher", image: "/images/quantum.jpg" },
    { id: 33, title: "Aerospace Engineer", image: "/images/aerospace.jpg" },
    { id: 34, title: "Agricultural Tech Expert", image: "/images/agritech.jpg" },
    { id: 35, title: "Genetic Engineer", image: "/images/genetic-engineer.jpg" },
    { id: 36, title: "Space Scientist", image: "/images/space-scientist.jpg" },
    { id: 37, title: "Content Creator", image: "/images/content-creator.jpg" },
    { id: 38, title: "VR/AR Artist", image: "/images/vr-artist.jpg" },
    { id: 39, title: "Fashion Technologist", image: "/images/fashion-tech.jpg" },
    { id: 40, title: "Biomedical Engineer", image: "/images/biomedical.jpg" },
    { id: 41, title: "Social Media Manager", image: "/images/social-media.jpg" },
    { id: 42, title: "Creative Director", image: "/images/creative-director.jpg" },
    { id: 43, title: "Supply Chain Analyst", image: "/images/supply-chain.jpg" },
    { id: 44, title: "Renewable Energy Consultant", image: "/images/renewable-energy.jpg" },
    { id: 45, title: "Pharmaceutical Scientist", image: "/images/pharma.jpg" },
    { id: 46, title: "AI Chatbot Developer", image: "/images/ai-chatbot.jpg" },
    { id: 47, title: "Insurance Analyst", image: "/images/insurance.jpg" },
    { id: 48, title: "Cyber Crime Analyst", image: "/images/cyber-crime.jpg" },
    { id: 49, title: "Biochemist", image: "/images/biochemist.jpg" },
    { id: 50, title: "Neuroscientist", image: "/images/neuroscientist.jpg" },
  ];
  
  export default CareerData;
  